# Generated by Django 3.1 on 2020-09-01 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realtor',
            options={'ordering': ('-hire_date',)},
        ),
    ]
